name: 'NuGet: Get version from file name' 
description: Parses the file name
inputs:
  path: 
    description: 'The path to the package'
    required: true
    default: '*.nupkg'
outputs:
  name:
    description: 'The name of the package'
    value: ${{ steps.package.outputs.name }}
  version: 
    description: 'The version of the package, without build metadata.'
    value: ${{ steps.package.outputs.version }}

runs:
  using: "composite"
  steps:
  
    - name: File name
      id: file
      run: echo "::set-output name=name::$(echo $(basename ${{ inputs.path }}))"
      shell: bash
      
    - name: Parse Package
      id: package
      uses: actions/github-script@v5
      with:
        result-encoding: string
        script: |
          var matches = "${{ steps.file.outputs.name }}".match(/^(.*?)\.((?:\.?[0-9]+){3,}(?:[-a-z1-9]+?\.?)*)\.nupkg$/);
          console.log("::set-output name=name::" + matches[1])
          console.log("::set-output name=version::" + matches[2])
  
