name: 'NuGet: Generate SemVer suffix' 
description: Uses the GitHub context to generate the SemVer suffix for releases, pull requests and feature branches
inputs:
  default_branch:
    description: 'Name of default branch, e.g. main'
    type: string
    default: ${{ github.event.repository.default_branch }}
outputs:
  suffix: 
    description: 'The SemVer suffix to use'
    value: ${{ steps.suffix.outputs.result }}

runs:
  using: "composite"
  steps:  
    - name: Get short head SHA
      id: git
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      shell: bash
      
    - name: "Generate suffix"
      id: suffix
      uses: actions/github-script@v5
      with:
        result-encoding: string
        script: |
          console.log("Ref: " + context.ref);
          if (context.ref == 'refs/heads/${{ inputs.default_branch }}' && context.eventName == 'push') {
            return "+${{ steps.git.outputs.sha_short }}";
          } else if (context.eventName == 'pull_request') {
            return "-pull-request." + context.payLoad.pull_request.number + "+${{ steps.git.outputs.sha_short }}";
          } else if (context.eventName == 'push') {       
            return "-" + context.ref.substring(11).replace('/', '.') + "+${{ steps.git.outputs.sha_short }}";
          }        
