# uses: mikaeldui/actions/riot-games/league-of-legends/data-dragon/version@main
name: 'Data Dragon Version'
description: 'Get the latest version number of Data Dragon'
outputs:
  version: 
    description: 'The latest version number'
    value: ${{ steps.version.outputs.result }}    

runs:
  using: "composite"
  steps:  
    - name: Get the description
      if: ${{ inputs.description == null }}
      id: version
      uses: actions/github-script@v5
      with:
        result-encoding: string
        script: |       
          var https = require('https');

          var options = {
              host: 'ddragon.leagueoflegends.com',
              path: '/api/versions.json',
              headers: {'User-Agent': 'GitHubActions/main (https://github.com/mikaeldui/actions/tree/main/riot-games/league-of-legends/data-dragon/version)'}
          };

          return await https.get(options, function (res) {
              var json = '';
              res.on('data', function (chunk) {
                  json += chunk;
              });
              res.on('end', function () {
                  if (res.statusCode === 200) {
                      try {
                          var data = JSON.parse(json);
                          // data is available here:
                          return data[0];
                      } catch (e) {
                          console.log('Error parsing JSON!');
                      }
                  } else {
                      console.log('Status:', res.statusCode);
                  }
              });
          }).on('error', function (err) {
                console.log('Error:', err);
          });
      
