name: '.NET Pack & Publish as Artifact'
description: Packs NuGet and publishes as artifacts
inputs:
  version: 
    description: 'The version of the package'
    required: true
  project_directory:
    description: 'The path of the package'
    required: true
  configuration:
    description: 'The build configuration'
    required: true
    default: Release
  relative_package_path:
    description: 'The relative path to the package from the project directory'
    required: true
    default: '/bin/Release/*.nupkg'
  artifact_name:
    description: 'The name of the artifact'
    required: true
    default: nupkg

runs:
  using: "composite"
  steps:
    - name: Get project directory
      if: ${{ inputs.project_directory == null }}
      uses: mikaeldui/actions/nupkg/project-directory@main
      id: project-directory
  
    - name: Pack
      working-directory: ${{ inputs.project_directory }}${{ steps.project-directory.outputs.directory }}
      run: dotnet pack --configuration ${{ inputs.configuration }} --no-build /p:Version=${{ inputs.version }}
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ${{ inputs.project_directory }}${{ steps.project-directory.outputs.directory }}${{ inputs.relative_package_path }}
