name: 'Main Project Directory' 
description: 'Get the directory of the main project'
outputs:
  directory: 
    description: 'Project directory.'
    value: ${{ steps.directory.outputs.directory }}

runs:
  using: "composite"
  steps:
    - name: Parse version
      id: directory
      run: |
        project_directory=$(find * -maxdepth 0 -type d | xargs -d $'\n' sh -c 'for arg do find * -maxdepth 0 -type d | grep -wo "$arg"; done' _ \
        | sort | uniq -c | sort -nr | head  -1 | echo "./$(awk '{print $2}')")
        echo "::set-output name=directory::$(echo $project_directory)"
      shell: bash
