name: .NET Push 
description: Pushed the package to NuGet.org and/or GitHub.com
inputs:
  path: 
    description: 'The path to the package'
    required: true
    default: '*.nupkg'
  GITHUB_TOKEN:
    type: string
  NUGET_ORG_API_KEY:
    type: string
outputs:
  github_packages_url:
    description: The URL of the page for this package version
    value: ${{ steps.github_packages.outputs.url }}
  nuget_org_url:
    description: The URL of the page for this package version
    value: ${{ steps.nuget_org.outputs.url }}
runs:
  using: "composite"
  steps:
  
    - name: Push package to GitHub.com
      if: ${{ inputs.GITHUB_TOKEN != null }}
      id: github_packages
      uses: mikaeldui/actions/nupkg/github-packages/push@main
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      
    - name: Push Package to NuGet.org
      if: ${{ inputs.NUGET_ORG_API_KEY != null }}
      id: nuget_org
      uses: mikaeldui/actions/nupkg/nuget.org/push@main
      with:
        NUGET_ORG_API_KEY: ${{ inputs.NUGET_ORG_API_KEY }}
