name: 'Delete GitHub package versions' 
description: Used for retention policies
inputs:

  package-name:
    description: 'Name of the package containing the version to delete.'
    required: true
    
  version-type:
    description: 'Either release, pre-release or both.'
    required: true
    
  versions-to-keep:
    description: 'Number of versions to keep starting with the latest version. By default keeps no version. To delete all versions set this as 0.'
    required: false
    default: "-1"
    
runs:
  using: "composite"
  steps:  
  
  - name: 'Release retention'
    if: ${{ inputs.version-type == 'release' }}
    uses: actions/delete-package-versions@v2
    with:
      package-name: ${{ inputs.package-name }}
      min-versions-to-keep: ${{ inputs.versions-to-keep }}
      ignore-versions: ^((?:\.?[0-9]+){3,}(?:[-a-z0-9]+?\.?)+)$

  - name: 'Pre-release retention'
    if: ${{ inputs.version-type == 'pre-release' }}
    uses: actions/delete-package-versions@v2
    with:
      package-name: ${{ inputs.package-name }}
      min-versions-to-keep: ${{ inputs.versions-to-keep }}
      delete-only-pre-release-versions: "true" 
      
  - name: 'Retention'
    if: ${{ inputs.version-type == 'both' }}
    uses: actions/delete-package-versions@v2
    with:
      package-name: ${{ inputs.package-name }}
      min-versions-to-keep: ${{ inputs.versions-to-keep }}
