name: 'Create a tag' 
description: Used for releases
inputs:
  custom_tag:
    description: 'A custom tag'
    required: false
  release_branch:
    description: 'Name of default branch, e.g. main'
    type: string
    default: ${{ github.event.repository.default_branch }}
  dry_run:
    description: "Don't create the tag"
    required: false
    default: "false"
  GITHUB_TOKEN:
    type: string
    required: true
outputs:
  tag: 
    description: 'The tag'
    value: ${{ steps.tag.outputs.new_tag }}
  version:
    description: 'Version in tag'
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:  
    - name: Create tag
      id: tag
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        release_branches: ${{ inputs.default_branch }}
        dry_run: ${{ inputs.dry_run }}  
        custom_tag: ${{ inputs.custom_tag }}

    - name: Create version
      id: version
      run: |
        version=$(echo ${{ steps.tag.outputs.new_tag }} | cut -c2-)
        echo "::set-output name=version::$version"
      shell: bash
