name: .NET Build & Pack

on:
  workflow_call:
    inputs:
      project_directory:
        description: "The directory of the project, if it's not in the root or can't be found."
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: mikaeldui/actions/dotnet/setup@main
        
    - name: Get next version tag
      id: tag
      uses: mikaeldui/actions/create-tag@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        
    - name: Create SemVer suffix
      id: semver
      uses: mikaeldui/actions/nupkg/semver-suffix@main
      
      # Build & Test
        
    - name: Restore dependencies
      run: dotnet restore
      shell: bash      
      
    - name: .NET Build
      uses: mikaeldui/actions/nupkg/dotnet/build@main
      with:
        version: ${{ steps.tag.outputs.version }}${{ steps.semver.outputs.suffix }}
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      shell: bash
      
      # Pack & Publish
      
    - name: 'Pack & Publish Artifact'
      uses: mikaeldui/actions/nupkg/dotnet/pack-and-publish-artifact@main
      with:
        version: ${{ steps.tag.outputs.version }}${{ steps.semver.outputs.suffix }}
        project_directory: ${{ inputs.project_directory }}
