name: GitHub Packages Retention Policy
on: 
  workflow_call:
    inputs:
      package-type:
        description: 'One of the package types available'
        default: NUGET
        type: string
jobs:
  scout:
    name: 'Get package names'
    runs-on: ubuntu-latest
    outputs:
      package-names: ${{ steps.package_list.outputs.result }}
    steps:
      - uses: actions/github-script@v5
        id: package_list
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name) { 
                packages(packageType:${{ inputs.package-type }}, first:100) {
                  edges {
                    node {
                      name
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner
              name: context.repo.name
            }
            const result = await github.graphql(query, variables)
            return result.repository.packages.edges.map(({ node }) => node.name)            

  retention:
    name: 'Apply retention policy'
    runs-on: ubuntu-latest
    needs: scout
    strategy:
      matrix: 
        package: ${{ fromJSON(needs.scout.outputs.package-names) }}
    steps:
      - name: 'Release retention'
        uses: mikaeldui/actions/delete-package-versions@main
        with:
          package-name: ${{ matrix.package }}
          versions-to-keep: 10
          version-type: release
          
      - name: 'Pre-release retention'
        uses: mikaeldui/actions/delete-package-versions@main
        with:
          package-name: ${{ matrix.package }}
          versions-to-keep: 30
          version-type: pre-release 
