name: GitHub Packages Deploy
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the nupkg artifact
        type: string
        default: nupkg  
    outputs:
      url:
        description: The Github Packages URL for the package
        value: ${{ jobs.push.outputs.url }}
jobs:
  push:
    name: 'Push to GitHub Packages'
    runs-on: ubuntu-latest
    environment: 
      name: github-packages
      url: ${{ steps.push.outputs.url }}
    outputs:
      url:
        description: The Github Packages URL for the package
        value: ${{ steps.push.outputs.url }}

    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Download NuGet Package Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
      
      - name: Push
        uses: mikaeldui/actions/nupkg/github-packages/push@main
        id: push
        with:
          GITHUB_TOKEN: ${{ github.token }}
