name: NuGet.org Deployment
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the nupkg artifact
        type: string
        default: nupkg      
      snupkg_artifact_name:
        description: 'Path to any snupkg'
        type: string
        default: snupkg
    secrets:
      NUGET_ORG_API_KEY:
        required: true
    outputs:
      url:
        description: The NuGet.org URL for the package
        value: ${{ jobs.push.outputs.url }}
jobs:
  push:
    name: 'Push to NuGet.org'
    if: ${{ (github.ref_name == github.event.repository.default_branch && github.event_name == 'push') || github.event_name == 'pull_request' || (startsWith(github.ref, 'refs/heads/features') && github.event_name == 'push') }}
    runs-on: ubuntu-latest
    environment: 
      name: nuget.org
      url: ${{ steps.push.outputs.url}}
    outputs:
      url: ${{ steps.push.outputs.url }}

    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Download NuGet Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}          
          
      - name: Download NuGet Source Package Artifact
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: ${{ inputs.snupkg_artifact_name }}
        
      - name: Push
        uses: mikaeldui/actions/nupkg/nuget.org/push@main
        id: push
        with:
          NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
          snupkg: ${{ inputs.snupkg_artifact_name }}
