name: NuGet.org Deployment
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the nupkg artifact
        type: string
        default: nupkg      
    secrets:
      NUGET_ORG_API_KEY:
        required: true
    outputs:
      url:
        description: The NuGet.org URL for the package
        value: ${{ jobs.push.outputs.url }}
jobs:
  push:
    name: 'Push to NuGet.org'
    runs-on: ubuntu-latest
    environment: 
      name: nuget.org
      url: ${{ steps.nuget_org.outputs.url}}
    outputs:
      url:
        description: The NuGet.org URL for the package
        value: ${{ steps.push.outputs.url }}

    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Download NuGet Package Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
        
      - name: Push
        uses: mikaeldui/actions/nupkg/nuget.org/push@main
        id: push
        with:
          NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
